// Shared mock database for orders - in production, replace with real database
export let orders: any[] = [
  {
    id: 'ORD-1234567890',
    userId: 'user-123',
    items: [
      {
        id: 'order-item-1',
        artworkId: 'art-1',
        quantity: 1,
        price: 450,
        title: 'Chromatic Pulse',
        artistId: 'artist-1',
      },
    ],
    subtotal: 450,
    tax: 45,
    shipping: 50,
    discount: 0,
    total: 545,
    currency: 'INR',
    status: 'placed',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    shippingAddress: {
      id: 'addr-1',
      userId: 'user-123',
      type: 'home',
      name: 'Casey Buyer',
      phone: '1234567890',
      addressLine1: '123 Main St',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      country: 'India',
      isDefault: true,
    },
    billingAddress: {
      id: 'addr-1',
      userId: 'user-123',
      type: 'home',
      name: 'Casey Buyer',
      phone: '1234567890',
      addressLine1: '123 Main St',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      country: 'India',
      isDefault: true,
    },
    orderDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedDelivery: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    actualDelivery: null,
    trackingNumber: 'TN1234567890',
    notes: null,
    cancellationReason: null,
    cancellationComments: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ORD-1234567891',
    userId: 'user-123',
    items: [
      {
        id: 'order-item-2',
        artworkId: 'art-2',
        quantity: 1,
        price: 780,
        title: 'The Whispering City',
        artistId: 'artist-2',
      },
    ],
    subtotal: 780,
    tax: 78,
    shipping: 50,
    discount: 0,
    total: 908,
    currency: 'INR',
    status: 'confirmed',
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    shippingAddress: {
      id: 'addr-1',
      userId: 'user-123',
      type: 'home',
      name: 'Casey Buyer',
      phone: '1234567890',
      addressLine1: '123 Main St',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      country: 'India',
      isDefault: true,
    },
    billingAddress: {
      id: 'addr-1',
      userId: 'user-123',
      type: 'home',
      name: 'Casey Buyer',
      phone: '1234567890',
      addressLine1: '123 Main St',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      country: 'India',
      isDefault: true,
    },
    orderDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedDelivery: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    actualDelivery: null,
    trackingNumber: 'TN1234567891',
    notes: null,
    cancellationReason: null,
    cancellationComments: null,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ORD-1234567892',
    userId: 'user-123',
    items: [
      {
        id: 'order-item-3',
        artworkId: 'art-3',
        quantity: 1,
        price: 600,
        title: 'Serenity in Crimson',
        artistId: 'artist-3',
      },
    ],
    subtotal: 600,
    tax: 60,
    shipping: 50,
    discount: 0,
    total: 710,
    currency: 'INR',
    status: 'packed',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    shippingAddress: {
      id: 'addr-1',
      userId: 'user-123',
      type: 'home',
      name: 'Casey Buyer',
      phone: '1234567890',
      addressLine1: '123 Main St',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      country: 'India',
      isDefault: true,
    },
    billingAddress: {
      id: 'addr-1',
      userId: 'user-123',
      type: 'home',
      name: 'Casey Buyer',
      phone: '1234567890',
      addressLine1: '123 Main St',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      country: 'India',
      isDefault: true,
    },
    orderDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedDelivery: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    actualDelivery: null,
    trackingNumber: 'TN1234567892',
    notes: null,
    cancellationReason: null,
    cancellationComments: null,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ORD-1234567893',
    userId: 'user-123',
    items: [
      {
        id: 'order-item-4',
        artworkId: 'art-4',
        quantity: 1,
        price: 320,
        title: 'Emerald Valley',
        artistId: 'artist-1',
      },
    ],
    subtotal: 320,
    tax: 32,
    shipping: 50,
    discount: 0,
    total: 402,
    currency: 'INR',
    status: 'shipped',
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    shippingAddress: {
      id: 'addr-1',
      userId: 'user-123',
      type: 'home',
      name: 'Casey Buyer',
      phone: '1234567890',
      addressLine1: '123 Main St',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      country: 'India',
      isDefault: true,
    },
    billingAddress: {
      id: 'addr-1',
      userId: 'user-123',
      type: 'home',
      name: 'Casey Buyer',
      phone: '1234567890',
      addressLine1: '123 Main St',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      country: 'India',
      isDefault: true,
    },
    orderDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedDelivery: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    actualDelivery: null,
    trackingNumber: 'TN1234567893',
    notes: null,
    cancellationReason: null,
    cancellationComments: null,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ORD-1234567894',
    userId: 'user-123',
    items: [
      {
        id: 'order-item-5',
        artworkId: 'art-5',
        quantity: 1,
        price: 950,
        title: 'Digital Dreamscape',
        artistId: 'artist-2',
      },
    ],
    subtotal: 950,
    tax: 95,
    shipping: 50,
    discount: 0,
    total: 1095,
    currency: 'INR',
    status: 'delivered',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    shippingAddress: {
      id: 'addr-1',
      userId: 'user-123',
      type: 'home',
      name: 'Casey Buyer',
      phone: '1234567890',
      addressLine1: '123 Main St',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      country: 'India',
      isDefault: true,
    },
    billingAddress: {
      id: 'addr-1',
      userId: 'user-123',
      type: 'home',
      name: 'Casey Buyer',
      phone: '1234567890',
      addressLine1: '123 Main St',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      country: 'India',
      isDefault: true,
    },
    orderDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedDelivery: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    actualDelivery: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    trackingNumber: 'TN1234567894',
    notes: null,
    cancellationReason: null,
    cancellationComments: null,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
